### ISSUE TITLE
Crawling train, dev, and test set

### ISSUE THREAD

**Issue by ASoleimaniB** [hfthair/emerald_crawler#2]
Does the explanation in the readme file lead to all three sets? I mean after running `download` and `csv2json`, we would have 3 separate files? Or do we need any extra steps to generate them?

**Comment by ASoleimaniB** [comment]
Also, I see that you have `train.url` file but does the code use that? I mean does the current code and instruction exactly crawl the data you had experiments on?

**Comment by hfthair** [comment]
* `download` and `csv2json` will only generate one `jsonl` file. You will need extra steps to split it into train/dev/split.  
* It is not very likely that you can crawl exactly the data we experiment on, because you may have access to a different portion of the Emerald data set.
* And that is the reason we publish `data/train|dev|test.url`. The code does not use the `*.url` files, but you can split your dataset according to our train/dev/test (using URL as unique ID), then you get the exact data.
